Set i circles / 1*7 /;
Alias(i,j);
Variables x(i), y(i), radius;
x.lo(i) = 0; x.up(i) = 1;
y.lo(i) = 0; y.up(i) = 1;
Equations non_overlap(i,j), boundary1(i), boundary2(i), boundary3(i);
boundary1(i).. x(i) =g= radius;
boundary2(i).. y(i) =g= radius;
boundary3(i).. (1 - x(i) - y(i)) / sqrt(2) =g= radius;
non_overlap(i,j)$(ord(j)>ord(i)).. power(x(i) - x(j), 2) + power(y(i) - y(j), 2) =g= power(2 * radius, 2);
Model m / all /;
m.optfile = 1;
Solve m using nlp maximizing radius;
